import { dashboardTool } from "./dashboard.ts";
import {
	episodeAddNoteTool,
	episodeDeleteTool,
	episodeEndTool,
	episodeGetTool,
	episodeListTool,
	episodeStartTool,
	episodeUpdateTool,
} from "./episode.ts";
import {
	examDeleteTool,
	examGetTool,
	examListTool,
	examMetricSeriesTool,
	examPasteTool,
	examUpdateTool,
	examUploadTool,
} from "./exam.ts";
import { episodeInsightsTool } from "./insights.ts";
import {
	petCreateTool,
	petDeleteTool,
	petEnrichTool,
	petGetTool,
	petListTool,
	petUpdateTool,
} from "./pet.ts";
import {
	prescriptionCreateTool,
	prescriptionDeleteTool,
	prescriptionListTool,
	prescriptionUpdateTool,
	prescriptionUploadTool,
} from "./prescription.ts";
import {
	pushSubscribeTool,
	pushTestTool,
	pushUnsubscribeTool,
	pushVapidPublicKeyTool,
} from "./push.ts";
import {
	recordingAddChunkTool,
	recordingApplyGroupTool,
	recordingApplyTool,
	recordingCreateTool,
	recordingGetTool,
	recordingListTool,
	recordingSummarizeTool,
	recordingTranscribeTool,
} from "./recording.ts";
import { vetResearchTool } from "./research.ts";
import {
	doseLogTool,
	doseUpdateTool,
	scheduleStateDeleteTool,
	scheduleStateListTool,
	timetableGetTool,
	timetableSetAnchorTool,
	timetableSetDurationTool,
	timetableSnoozeTool,
	timetableStopItemTool,
} from "./timetable.ts";

export const tools = [
	dashboardTool,
	petCreateTool,
	petUpdateTool,
	petDeleteTool,
	petEnrichTool,
	petGetTool,
	petListTool,
	episodeStartTool,
	episodeGetTool,
	episodeListTool,
	episodeUpdateTool,
	episodeEndTool,
	episodeDeleteTool,
	episodeAddNoteTool,
	prescriptionUploadTool,
	prescriptionCreateTool,
	prescriptionUpdateTool,
	prescriptionListTool,
	prescriptionDeleteTool,
	examUploadTool,
	examPasteTool,
	examUpdateTool,
	examDeleteTool,
	examGetTool,
	examListTool,
	examMetricSeriesTool,
	timetableGetTool,
	scheduleStateListTool,
	scheduleStateDeleteTool,
	doseLogTool,
	doseUpdateTool,
	timetableSnoozeTool,
	timetableSetAnchorTool,
	timetableStopItemTool,
	timetableSetDurationTool,
	recordingCreateTool,
	recordingAddChunkTool,
	recordingTranscribeTool,
	recordingSummarizeTool,
	recordingApplyTool,
	recordingApplyGroupTool,
	recordingGetTool,
	recordingListTool,
	episodeInsightsTool,
	vetResearchTool,
	pushVapidPublicKeyTool,
	pushSubscribeTool,
	pushUnsubscribeTool,
	pushTestTool,
];
